services:
  homeflix:
    build: .
    container_name: homeflix
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./homeflix.db:/app/homeflix.db
      - ./templates:/app/templates
      - ./static:/app/static
      - ./css:/app/css
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1

  sync-scheduler:
    build: .
    container_name: homeflix-sync
    restart: always
    volumes:
      - ./homeflix.db:/app/homeflix.db
    environment:
      - PYTHONUNBUFFERED=1
    command: python sync_scheduler.py
